name: store_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.3
  elevarm_ui: ^0.11.1
  hugeicons: ^0.0.7
  google_fonts: ^6.2.1
  flutter_bloc: ^9.0.0
  data_table_2: ^2.5.18
  toastification: ^2.3.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
